apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: listik-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
        - name: user-service
          image: 590183877725.dkr.ecr.ap-northeast-2.amazonaws.com/user-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USER_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USER_DATASOURCE_PASSWORD
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_SERVICE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: SERVICE_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SERVICE_AUTH_SECRET
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            failureThreshold: 30 # 30번 실패할 때까지 기다림 (30 * 10초 = 최대 5분)
            periodSeconds: 10
          
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 10 # startupProbe 성공 후 10초 뒤부터 시작
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 5  # startupProbe 성공 후 5초 뒤부터 시작
            periodSeconds: 10


---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: listik-prod
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
