apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-creds-refresh
  namespace: listik-prod
spec:
  # 11시간마다 실행 (매일 0시/11시/22시)
  schedule: "0 */11 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          restartPolicy: OnFailure
          containers:
          - name: ecr-creds-refresh
            image: amazon/aws-cli:2.15.34
            command:
              - /bin/sh
              - -c
              - |
                PASSWORD=$(aws ecr get-login-password --region ap-northeast-2)
                kubectl -n listik-prod create secret docker-registry ecr-creds \
                  --docker-server=590183877725.dkr.ecr.ap-northeast-2.amazonaws.com \
                  --docker-username=AWS \
                  --docker-password="$PASSWORD" \
                  --dry-run=client -o yaml | kubectl apply -f -
            env:
              - name: AWS_REGION
                value: ap-northeast-2
            volumeMounts:
              - name: aws-config
                mountPath: /root/.aws
                readOnly: true
          volumes:
            - name: aws-config
              secret:
                secretName: aws-credentials
